### ISSUE TITLE
Incorrect ESLint rules

### ISSUE THREAD

**Issue by Kevin-ishimwe** [atlp-rwanda/ecommerce-app-legends-fe#10]
### Description
Our project's ESLint rules were not properly configured, resulting in a lot of errors being thrown. This is causing significant productivity loss and slowing down our development process.

### Steps to Reproduce
1. Clone the project
2. Run the project locally
3. Observe the numerous ESLint errors in the console

### Expected behavior
ESLint rules should be properly configured and the project should not throw any errors.

### Actual behavior
Numerous errors are being thrown due to incorrect ESLint rules.

### Possible Solution
We need to review and update our ESLint rules to ensure they are properly configured and in line with our project requirements.

### Reproducibility
The issue is reproducible on every machine that runs the project.

### Severity/Impact
This issue is causing significant productivity loss and slowing down our development process.

### Environment
- Operating System:
- Browser:
- Node.js version:
- ESLint version:

### Steps taken to resolve
We have attempted to resolve the issue by reviewing and updating the ESLint rules, but the issue persists.

### Screenshots
Please find attached a screenshot of the console showing the numerous ESLint errors.
![eslint](https://user-images.githubusercontent.com/107407670/233469113-36d97f50-f898-4342-a4e5-1977e4b3f3bc.PNG)

### Additional Information
- The project is built using Node.js and React.
- We are using ESLint version 7.32.0.
- We have not made any recent changes to the project that may have caused this issue.

**Comment by Aimeana100** [comment]
👍
